// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'event_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2736796775319796425),
    name: 'TrackEvent',
    lastPropertyId: const obx_int.IdUid(9, 5537782633562139323),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1380186693502817881),
        name: 'objectBoxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8619091395222608586),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2581308046600192405),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3253106583983921210),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4229437394869768248),
        name: 'propertiesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8153533596792190550),
        name: 'commonPropertiesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6510402691561336668),
        name: 'distinctId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2501460499730254110),
        name: 'anonymousId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5094676419607860951),
        name: 'sessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5537782633562139323),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2736796775319796425),
    lastIndexId: const obx_int.IdUid(1, 2581308046600192405),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TrackEvent: obx_int.EntityDefinition<TrackEvent>(
      model: _entities[0],
      toOneRelations: (TrackEvent object) => [],
      toManyRelations: (TrackEvent object) => {},
      getId: (TrackEvent object) => object.objectBoxId,
      setId: (TrackEvent object, int id) {
        object.objectBoxId = id;
      },
      objectToFB: (TrackEvent object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final propertiesJsonOffset = fbb.writeString(object.propertiesJson);
        final commonPropertiesJsonOffset = fbb.writeString(
          object.commonPropertiesJson,
        );
        final distinctIdOffset =
            object.distinctId == null ? null : fbb.writeString(object.distinctId!);
        final anonymousIdOffset =
            object.anonymousId == null ? null : fbb.writeString(object.anonymousId!);
        final sessionIdOffset = fbb.writeString(object.sessionId);
        fbb.startTable(10);
        fbb.addInt64(0, object.objectBoxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, propertiesJsonOffset);
        fbb.addOffset(4, commonPropertiesJsonOffset);
        fbb.addOffset(5, distinctIdOffset);
        fbb.addOffset(6, anonymousIdOffset);
        fbb.addOffset(7, sessionIdOffset);
        fbb.addInt64(8, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.objectBoxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final objectBoxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final propertiesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final commonPropertiesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final distinctIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final anonymousIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = TrackEvent(
          objectBoxId: objectBoxIdParam,
          id: idParam,
          name: nameParam,
          propertiesJson: propertiesJsonParam,
          commonPropertiesJson: commonPropertiesJsonParam,
          sessionId: sessionIdParam,
          timestamp: timestampParam,
          distinctId: distinctIdParam,
          anonymousId: anonymousIdParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TrackEvent] entity fields to define ObjectBox queries.
class TrackEvent_ {
  /// See [TrackEvent.objectBoxId].
  static final objectBoxId = obx.QueryIntegerProperty<TrackEvent>(
    _entities[0].properties[0],
  );

  /// See [TrackEvent.id].
  static final id = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[1],
  );

  /// See [TrackEvent.name].
  static final name = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[2],
  );

  /// See [TrackEvent.propertiesJson].
  static final propertiesJson = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[3],
  );

  /// See [TrackEvent.commonPropertiesJson].
  static final commonPropertiesJson = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[4],
  );

  /// See [TrackEvent.distinctId].
  static final distinctId = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[5],
  );

  /// See [TrackEvent.anonymousId].
  static final anonymousId = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[6],
  );

  /// See [TrackEvent.sessionId].
  static final sessionId = obx.QueryStringProperty<TrackEvent>(
    _entities[0].properties[7],
  );

  /// See [TrackEvent.timestamp].
  static final timestamp = obx.QueryDateProperty<TrackEvent>(
    _entities[0].properties[8],
  );
}
