name: fast_track
description: Lightweight Flutter analytics SDK with session management, batching, retry, and ObjectBox persistence.
version: 0.1.0
homepage: https://github.com/18637780521yx/track
repository: https://github.com/18637780521yx/track
issue_tracker: https://github.com/18637780521yx/track/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_tools: ^0.1.0
  dio: ^5.7.0
  archive: ^4.0.0
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  flat_buffers: ^25.9.23
  path_provider: ^2.1.0
  path: ^1.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.0
  build_runner: ^2.4.13
  objectbox_generator: ^5.2.0

flutter:
  uses-material-design: false
